### ISSUE TITLE
Jet Coaster Lift Sounds from Youtube.

### ISSUE THREAD

**Issue by Jetcoasterfan** [Emonadeo/Nolimits2Sounds#1]
I found this very neat lifthill sound from the Chupy Coaster at Washuzan Highland Japan. https://www.youtube.com/watch?v=F4EVYEMXxw4 

I found this neat lifthill sound from Slope Shooter at Nagoya Higashiyama Zoo Japan. https://www.youtube.com/watch?v=E7n53-VkIYQ

I found this lifthill sound from Jet Coaster at Dreamland Koriyama Japan. https://www.youtube.com/watch?v=6lTr9etdlVc

Found this lifthill sound from Jet Coaster at Teine Olympia.
https://www.youtube.com/watch?v=x78MBz6Y85Y

Found this lifthill sound from Hurry Coaster at Kobe Fruit And Flower Park Japan. https://www.youtube.com/watch?v=IQfe4Vo8924

Found this lifthill sound from Jet Coaster at Kobe Fruit And Flower Park Japan. https://www.youtube.com/watch?v=ieSiRjK2yIA

**Comment by Emonadeo** [comment]
These are a lot of sounds. I probably wont add all of them so I am offering you to rank these sounds from 1 to 6 with 1 being your most favorite and 6 being your least favorite sound.

**Comment by Jetcoasterfan** [comment]
1 is the chupy coaster lift sound.  2 Is the Hurry Coaster coaster
roar/grind sound.  https://www.youtube.com/watch?v=IQfe4Vo8924  3 is the
Jet Coaster Lift sound https://www.youtube.com/watch?v=DMUmkPU3qSc

**Comment by Emonadeo** [comment]
Sorry for the late response. I'll make sure to implement what I can soon. :) Thanks for your patience
