### ISSUE TITLE
Maverick LSM Sound

### ISSUE THREAD

**Issue by InsanityBK04** [Emonadeo/Nolimits2Sounds#7]
https://youtu.be/BIJBz1w3uYw?t=5
I put the time where the noise is so you can hear it. I mean it is loud and you can hear it pretty well. It would be awesome if you add this!

**Comment by emonadeo** [comment]
Unfortunatly there is too much wind and other noises so I won't be able to implement that. However I have received a bunch of sounds from various other launches including Red Force and Volcano with a promising quality, so these will probably be added in the near future. Thanks for submitting anyways.
